version: '3.4'

services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    hostname: nexus3
    restart: always
    ports:
      - "8081:8081"
    volumes: 
      - nexus_data:/nexus-data
    networks:
      - app_net

volumes:
  nexus_data:
    name: nexus_data
networks:
  app_net:
    external: true
