version: '3.4'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_STANDLONE_ENABLED: false
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_log_data:/datalog
    networks:
      - app_net

volumes:
  zookeeper_data:
    name: zookeeper_data
  zookeeper_log_data:
    name: zookeeper_log_data
networks:
  app_net:
    external: true
