version: '3.4'

services:
  zookeeper1:
    image: zookeeper
    container_name: zookeeper1
    hostname: zookeeper1
    restart: always
    environment:
      - "ZOO_MY_ID: 1"
      - "ZOO_TICK_TIME: 2000"
      - "ZOO_INIT_LIMIT: 5"
      - "ZOO_SYNC_LIMIT: 2"
      - "ZOO_MAX_CLIENT_CNXNS: 60"
      - "ZOO_STANDLONE_ENABLED: false"
      - "ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888"
    ports:
      - "2181:2181"
    networks:
      - app_net
  zookeeper2:
    image: zookeeper
    container_name: zookeeper2
    hostname: zookeeper2
    restart: always
    environment:
      - "ZOO_MY_ID: 2"
      - "ZOO_TICK_TIME: 2000"
      - "ZOO_INIT_LIMIT: 5"
      - "ZOO_SYNC_LIMIT: 2"
      - "ZOO_MAX_CLIENT_CNXNS: 60"
      - "ZOO_STANDLONE_ENABLED: false"
      - "ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888"
    ports:
      - "2182:2181"
    networks:
      - app_net
  zookeeper3:
    image: zookeeper
    container_name: zookeeper3
    hostname: zookeeper3
    restart: always
    environment:
      - "ZOO_MY_ID: 3"
      - "ZOO_TICK_TIME: 2000"
      - "ZOO_INIT_LIMIT: 5"
      - "ZOO_SYNC_LIMIT: 2"
      - "ZOO_MAX_CLIENT_CNXNS: 60"
      - "ZOO_STANDLONE_ENABLED: false"
      - "ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888"
    ports:
      - "2183:2181"
    networks:
      - app_net

networks:
  app_net:
    external: true
