version: '3.4'

services:
  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Anowls@38
    ports:
      - "3306:3306"
    volumes:
      - e:/docker_volumes/mysql_data:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net:
    external: true
