version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config_data:/data/configdb
    networks:
      - app_net

volumes:
  mongo_data:
    name: mongo_data
  mongo_config_data:
    name: mongo_config_data
networks:
  app_net:
    external: true
