version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - e:/docker_volumes/mongo_data:/data/db
      - e:/docker_volumes/mongo_config_data:/data/configdb
    networks:
      - app_net

networks:
  app_net:
    external: true
